version: 0.1

phases:
  install:
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  build:
    commands:
      - apt-get update
      - apt-get --assume-yes install openssh-client
      - mkdir -p ~/.aws
      - echo "[default]\nregion = us-east-1" > ~/.aws/config
      - echo "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
      - mkdir -p ~/.ssh
      - echo $SSH_PRIVATE_KEY | base64 --decode -i > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
      - ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
      - docker-compose --version
      # Run enviroment
      - docker-compose -f docker-env.yml up -d
      # Run tests
      - docker-compose -f docker-test.yml run tests
      # Deploy package
      - git clone -v -b yandex git@github.com:hovel/deploy-inventory.git ../deploy-inventory
      - ls -l ../deploy-inventory
      - docker-compose -f docker-zappa.yml run deploy
      # Teardown enviroment
      - docker-compose -f docker-env.yml down
