web:
  build: .
  links:
    - db
    - mc
    - redis
  ports:
    - "8000:80"
    - "8022:22"
  environment:
    ROOT_PASS: 123
  volumes:
    - ".:/root/src"
  command: bash -c "cd /root/src/ && /var/venv/bin/python manage.py runserver 0.0.0.0:80"
  privileged: true
  dns:
    - 8.8.8.8
db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: local_db
  command: mysqld --character-set-server=utf8
mc:
  image: sylvainlasnier/memcached
redis:
  image: redis
