version: '2.1'
services:
  tests:
    build: .
    command: bash -c "cd /root/src/ && /var/venv/bin/python manage.py test aor --noinput"
    volumes:
      - ".:/root/src"
      - "~/.aws:/root/.aws"
    ports:
      - "8000:80"
