version: '2.1'
services:
  tests:
    build: .
    command: python -Wd /root/src/manage.py test aor --noinput
    volumes:
      - ".:/root/src"
      - "~/.aws:/root/.aws"
    ports:
      - "8000:80"
